name: 🔥 New SDK Request
description: Request a new OpenFGA SDK
labels: [ "sdk-request" ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new SDK request!

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have looked into the [README](https://github.com/openfga/sdk-generator/blob/main/README.md) and have not found a suitable solution or answer.
          required: true
        - label: I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
          required: true
        - label: I have searched the [issues](https://github.com/openfga/sdk-generator/issues) and have not found a suitable solution or answer.
          required: true
        - label: I have searched the [Slack Community](https://openfga.dev/community) and have not found a suitable solution or answer.
          required: true
        - label: I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true

  - type: textarea
    id: language
    attributes:
      label: SDK Language
      description: What language would you like us to support?
      placeholder: Ruby, PHP, Rust, ...
    validations:
      required: true

  - type: textarea
    id: language-version
    attributes:
      label: SDK Language Version
      description: What version of the language are you currently running?
      placeholder: Go 1.21.5, Python 3.11, Java 21, ...
    validations:
      required: true

  - type: textarea
    id: framework
    attributes:
      label: SDK Framework
      description: If this is a request to support a particular framework, let us know which.
      placeholder: SpringBoot, Express.js, Rails, ...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any references to other issues, PRs, documentation or other links
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
