name: Run Tests

on:
  merge_group:
  pull_request:

jobs:
  test-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Shellcheck
        run: make shellcheck

  build-and-test-js-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          repository: openfga/js-sdk
          path: clients/fga-js-sdk

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run SDK Tests
        run: make test-client-js

      - name: Check for SDK changes
        run: |
          cd clients/fga-js-sdk
          if $(git status | grep -q "nothing to commit"); then
            echo "CLEAN: no changes found"
            exit 0
          fi
          echo "DIRTY: changes found"
          git status
          git diff

  build-and-test-go-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          repository: openfga/go-sdk
          path: clients/fga-go-sdk

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run SDK Tests
        run: make test-client-go

      - name: Check for SDK changes
        run: |
          cd clients/fga-go-sdk
          if $(git status | grep -q "nothing to commit"); then
            echo "CLEAN: no changes found"
            exit 0
          fi
          echo "DIRTY: changes found"
          git status
          git diff

  build-and-test-dotnet-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          repository: openfga/dotnet-sdk
          path: clients/fga-dotnet-sdk

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run All Tests
        run: make test-client-dotnet

      - name: Check for SDK changes
        run: |
          cd clients/fga-dotnet-sdk
          if $(git status | grep -q "nothing to commit"); then
            echo "CLEAN: no changes found"
            exit 0
          fi
          echo "DIRTY: changes found"
          git status
          git diff


  build-and-test-python-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Specify python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          repository: openfga/python-sdk
          path: clients/fga-python-sdk

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run All Tests
        run: |-
          make test-client-python

      - name: Check for SDK changes
        run: |
          cd clients/fga-python-sdk
          if $(git status | grep -q "nothing to commit"); then
            echo "CLEAN: no changes found"
            exit 0
          fi
          echo "DIRTY: changes found"
          git status
          git diff

  build-and-test-java-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          repository: openfga/java-sdk
          path: clients/fga-java-sdk

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run All Tests
        run: |-
          make test-integration-client-java

      - name: Check for SDK changes
        run: |
          cd clients/fga-java-sdk
          if $(git status | grep -q "nothing to commit"); then
            echo "CLEAN: no changes found"
            exit 0
          fi
          echo "DIRTY: changes found"
          git status
          git diff
